version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    #      POSTGRES_DB: crm_customers
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  #    networks:
  #      - mynet
  go:
    container_name: go
    build:
      context: .
    #    ports:
    #      - "3000:3000"
    #    networks:
    #      - mynet
    depends_on:
      - "postgres"
#networks:
#  mynet:
#    driver: bridge
volumes:
  dbdata:
